### ISSUE TITLE
코드안에 개인정보가 포함됩니다.

### ISSUE THREAD

**Issue by BelBone** [DenFade/CovidhcheckTest#1]
```java
HcheckClient client = new HcheckClient("D100001756", "대진고등학교", "신호철", "021206", "dge");
```

**Comment by DenFade** [comment]
커밋 로그 전부 지우고 코드 args로 수정.

> ```java
> HcheckClient client = new HcheckClient(args[0], args[1], args[2], args[3], args[4]);
> ```
